FORMAT: 1A
HOST: https://subsplease-api.herokuapp.com/api/v1

# SubsPlease API
This API is Scrapes the [SubsPlease.org](https://subsplease.org/) Website and reads the RSS Feeds and Parses the Data as JSON!
<br>

## Written Documentation

### URLs 

#### **Base URL:** &nbsp;```https://subsplease-api.herokuapp.com/api/v1```


#### **Magnet Feed Link**
```
/feed/magnet/1080p
```
```
/feed/magnet/720p
```
```
/feed/magnet/sd
```
```
/feed/magnet/all
```

#### **Torrent Feed Link**
```
/feed/torrent/1080p
```
```
/feed/torrent/720p
```
```
/feed/torrent/sd
```
```
/feed/torrent/all
```

### JSON Example

#### **GET**
```
{
    "items": [
        {
            "title": "Video Title",
            "link": "Magnet/Torrent Link",
            "pubDate": "Pub Date",
            "guid": "GUID",
            "isoDate": "ISO Date"
        },
    ],
    "feedUrl": "http://subsplease.org/rss",
    "title": "SubsPlease RSS",
    "description": "RSS feed for SubsPlease releases (Resolution)",
    "link": "https://subsplease.org"
}
```

# Magnet Feed 1080p [/feed/magnet/1080p]

## GET Magnet Feed (1080p) [GET]
Magnet Feed Links for Anime in 1080p

+ Response 200 (application/json)
    + Attributes (Magnet Feed 1080p Response)


    + Body

            {
                "items": [
                    {
                        "title": "$title",
                        "link": "$magnet_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases (1080p)",
                "link": "https://subsplease.org"
            }



# Magnet Feed 720p [/feed/magnet/720p]

## GET Magnet Feed (720p) [GET]
720p Magnet Feed Links

+ Response 200 (application/json)
    + Attributes (Magnet Feed 720p Response)


    + Body

                        {
                "items": [
                    {
                        "title": "$title",
                        "link": "$magnet_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases (720p)",
                "link": "https://subsplease.org"
            }



# Magnet Feed SD [/feed/magnet/sd]

## GET Magnet Feed (SD) [GET]
SD Magnet Feed Links

+ Response 200 (application/json)
    + Attributes (Magnet Feed SD Response)


    + Body

           {
                "items": [
                    {
                        "title": "$title",
                        "link": "$magnet_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases (SD)",
                "link": "https://subsplease.org"
            }



# Magnet Feed All [/feed/magnet/all]

## GET Magnet Feed (All) [GET]
All Magnet Feed Links

+ Response 200 (application/json)
    + Attributes (Magnet Feed All Response)


    + Body

            {
                "items": [
                    {
                        "title": "$title",
                        "link": "$magnet_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases (All)",
                "link": "https://subsplease.org"
            }



# Torrent Feed 1080p [/feed/torrent/1080p]

## GET Torrent Feed (1080p) [GET]
1080p Torrent Feed Links

+ Response 200 (application/json)
    + Attributes (Torrent Feed 1080p Response)


    + Body

            {
                "items": [
                    {
                        "title": "$title",
                        "link": "$torrent_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases (1080p)",
                "link": "https://subsplease.org"
            }


# Torrent Feed 720p [/feed/torrent/720p]

## GET Torrent Feed (720p) [GET]
720p Torrent Feed Links

+ Response 200 (application/json)
    + Attributes (Torrent Feed 720p Response)


    + Body

            {
                "items": [
                    {
                        "title": "$title",
                        "link": "$torrent_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases (720p)",
                "link": "https://subsplease.org"
            }



# Torrent Feed SD [/feed/torrent/sd]

## GET Torrent Feed (SD) [GET]
SD Torrent Feed Links

+ Response 200 (application/json)
    + Attributes (Torrent Feed SD Response)


    + Body

            {
                "items": [
                    {
                        "title": "$title",
                        "link": "$torrent_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases (SD)",
                "link": "https://subsplease.org"
            }



# Torrent Feed All [/feed/torrent/all]

## GET Torrent Feed (All) [GET]
All Torrent Feed Links

+ Response 200 (application/json)
    + Attributes (Torrent Feed All Response)


    + Body

            {
                "items": [
                    {
                        "title": "$title",
                        "link": "$torrent_url",
                        "pubDate": "$date",
                        "guid": "$guid",
                        "isoDate": "$iso_date"
                    },
                ],
                "feedUrl": "http://subsplease.org/rss",
                "title": "SubsPlease RSS",
                "description": "RSS feed for SubsPlease releases ()",
                "link": "https://subsplease.org"
            }



# Data Structures

## Order (object)


### Properties
+ `id` (number, optional) 
+ `petId` (number, optional) 
+ `quantity` (number, optional) 
+ `shipDate` (string, optional) 
+ `status` (enum[string], optional) - Order Status
    + `placed`
    + `approved`
    + `delivered`
+ `complete`: `false` (boolean, optional) 


## Category (object)


### Properties
+ `id` (number, optional) 
+ `name` (string, optional) 


## User (object)


### Properties
+ `id` (number, optional) 
+ `username` (string, optional) 
+ `firstName` (string, optional) 
+ `lastName` (string, optional) 
+ `email` (string, optional) 
+ `password` (string, optional) 
+ `phone` (string, optional) 
+ `userStatus` (number, optional) - User Status


## Tag (object)


### Properties
+ `id` (number, optional) 
+ `name` (string, optional) 


## Pet (object)


### Properties
+ `id` (number, optional) 
+ `category` (Category, optional) 
+ `name` (string, required) 
+ `photoUrls` (array[string], required) 
+ `tags` (array[Tag], optional) 
+ `status` (enum[string], optional) - pet status in the store
    + `available`
    + `pending`
    + `sold`


## ApiResponse (object)


### Properties
+ `code` (number, optional) 
+ `type` (string, optional) 
+ `message` (string, optional) 


## Magnet Feed 1080p Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required) 


## Magnet Feed 720p Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required) 


## Magnet Feed All Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required) 


## Magnet Feed SD Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required) 


## Torrent Feed 1080p Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required) 


## Torrent Feed 720p Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required) 


## Torrent Feed All Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required) 


## Torrent Feed SD Response (object)


### Properties
+ `items` (array[object], required) 
+ `feedUrl` (string, required) 
+ `title` (string, required) 
+ `description` (string, required) 
+ `link` (string, required)